project:
  type: website
execute:
  freeze: auto
website:
  title: "InDaLab"
  site-url: "https://pbosetti.github.io/indalab/"
  navbar:
    left:
      - text: "Esperimenti"
        href: "experiments.qmd"
      - text: "Presentazioni"
        href: "slides.qmd"
    right:
      - icon: github
        href: "https://github.com/pbosetti/indalab"
format:
  html:
    lang: it
    theme: materia
    